export const BUILDING_REGISTRY = {
  road: { level: 1 },
  house1: { level: 1 },
  factory: { level: 1 },
  tower: { level: 1 },
  shop: { level: 1 },
  house2: { level: 2 },
  apartment: { level: 2 },
  clockTower: { level: 2 },
  skyscraper: { level: 3 },
  hospital: { level: 3 },
  fireStation: { level: 3 },
  school: { level: 4 },
  library: { level: 4 },
  bakery: { level: 4 },
};

export const UI_ELEMENT_IDS = {
  buyRoad: 'buyRoad',
  buyHouse1: 'buyHouse1',
  buyFactory: 'buyFactory',
  buyTower: 'buyTower',
  buyShop: 'buyShop',
  buyHouse2: 'buyHouse2',
  buyApartment: 'buyApartment',
  buyClockTower: 'buyClockTower',
  buySkyscraper: 'buySkyscraper',
  buyHospital: 'buyHospital',
  buyFireStation: 'buyFireStation',
  buySchool: 'buySchool',
  buyLibrary: 'buyLibrary',
  buyBakery: 'buyBakery',
  buyTreeA: 'buyTreeA',
  buyTreeB: 'buyTreeB',
  buyFlowerGarden: 'buyFlowerGarden',
  buyPark: 'buyPark',
  placementControls: 'placementControls',
  cancelPlacement: 'cancelPlacement',
  rotatePlacement: 'rotatePlacement',
  rotateViewLeft: 'rotateViewLeft',
  rotateViewRight: 'rotateViewRight',
  zoomIn: 'zoomIn',
  zoomOut: 'zoomOut',
  buildingActionMenu: 'buildingActionMenu',
  moveBuildingBtn: 'moveBuildingBtn',
  removeBuildingBtn: 'removeBuildingBtn',
  cancelBuildingActionBtn: 'cancelBuildingActionBtn',
};

export const HUD_ELEMENT_IDS = {
  levelTextEl: 'levelText',
  progressTextEl: 'progressText',
  happyPointsTextEl: 'happinessPointsText',
  happyTextEl: 'happyText',
};

export const STORE_ITEMS = [
  { id: 'buyRoad', placement: { type: 'road', cost: 0 } },
  { id: 'buyHouse1', placement: { type: 'house1', cost: 0 } },
  { id: 'buyFactory', placement: { type: 'factory', cost: 0 } },
  { id: 'buyTower', placement: { type: 'tower', cost: 0 } },
  { id: 'buyShop', placement: { type: 'shop', cost: 0 } },
  { id: 'buyHouse2', placement: { type: 'house2', cost: 0 } },
  { id: 'buyApartment', placement: { type: 'apartment', cost: 0 } },
  { id: 'buyClockTower', placement: { type: 'clockTower', cost: 0 } },
  { id: 'buySkyscraper', placement: { type: 'skyscraper', cost: 0 } },
  { id: 'buyHospital', placement: { type: 'hospital', cost: 0 } },
  { id: 'buyFireStation', placement: { type: 'fireStation', cost: 0 } },
  { id: 'buySchool', placement: { type: 'school', cost: 0 } },
  { id: 'buyLibrary', placement: { type: 'library', cost: 0 } },
  { id: 'buyBakery', placement: { type: 'bakery', cost: 0 } },
  { id: 'buyTreeA', placement: { type: 'treeA', cost: 10, isDecoration: true } },
  { id: 'buyTreeB', placement: { type: 'treeB', cost: 15, isDecoration: true } },
  { id: 'buyFlowerGarden', placement: { type: 'flowerGarden', cost: 25, isDecoration: true } },
  { id: 'buyPark', placement: { type: 'park', cost: 50, isDecoration: true } },
];

export const BUILDING_LABELS = {
  road: 'Road',
  house1: 'House 1',
  factory: 'Factory',
  tower: 'Tower',
  shop: 'Shop',
  house2: 'House 2',
  apartment: 'Apartment',
  clockTower: 'Clock Tower',
  skyscraper: 'Skyscraper',
  hospital: 'Hospital',
  fireStation: 'Fire Station',
  school: 'School',
  library: 'Library',
  bakery: 'Bakery',
  treeA: 'Tree A',
  treeB: 'Tree B',
  flowerGarden: 'Garden',
  park: 'Park',
};

export const LEVEL_BUTTON_TYPES = {
  buyHouse1: 'house1',
  buyFactory: 'factory',
  buyTower: 'tower',
  buyShop: 'shop',
  buyHouse2: 'house2',
  buyApartment: 'apartment',
  buyClockTower: 'clockTower',
  buySkyscraper: 'skyscraper',
  buyHospital: 'hospital',
  buyFireStation: 'fireStation',
  buySchool: 'school',
  buyLibrary: 'library',
  buyBakery: 'bakery',
};

export const DECORATION_BUTTON_TYPES = {
  buyTreeA: 'treeA',
  buyTreeB: 'treeB',
  buyFlowerGarden: 'flowerGarden',
  buyPark: 'park',
};
